[package]
name = "rocket-ts"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.62"
syn = { version = "1.0", features = ["full", "visit"] }
quote = "1.0"
clap = { version = "4.5.2", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.3"
