/*
 * Generated by rocket-ts 0.1.0 🚀 🌎
 */
   
   export interface k7 {
    // thread.rs
    // Route: "/thread/<kid_or_cerb_mask>"
    get_thread: (service:AgentService) => Thread;
    // Route: "/debug/thread/<kid>"
    get_thread_debug: (service:AgentService) => ThreadDebug;
    // Route: "/thread/<thread_id>/comments"
    get_thread_comments: (thread_id:i32,service:AgentService) => Comment[];
    // Route: "/thread/<thread_id>/insights"
    get_thread_insights: (thread_id:i32,service:AgentService) => MessageInsights;
    // Route: "/thread/escalate"
    escalate_thread: (ThreadEscalation) => any;
}